//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/EntradaMovimiento.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @EntradaMovimiento : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @EntradaMovimiento()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""EntradaMovimiento"",
    ""maps"": [
        {
            ""name"": ""Movimiento"",
            ""id"": ""a4d4f3d8-bcda-4ae0-a948-50efd76ed944"",
            ""actions"": [
                {
                    ""name"": ""Horizontal"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7e75e254-a38c-4b8e-8127-728275b8ac94"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Vertical"",
                    ""type"": ""Button"",
                    ""id"": ""685a8670-2bb3-4216-aaf3-fddb3a6b8b10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""54b977f3-7e60-4b4d-a1e9-2e712e513725"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Speed"",
                    ""type"": ""Value"",
                    ""id"": ""797fed93-2121-497b-8afa-0f85b18f2273"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Stop"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d4b1196f-bdfa-4dfe-a210-991fb810f6ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Acelerar"",
                    ""type"": ""PassThrough"",
                    ""id"": ""bf05affa-f774-44d9-986f-c37658526fa5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Desacelerar"",
                    ""type"": ""PassThrough"",
                    ""id"": ""19a1a01d-cc12-413c-ad4e-9496ac8ad797"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Flechas"",
                    ""id"": ""22769aa6-aedd-465f-b23a-d9afb590579e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c3baa304-b10f-4aae-a23b-83004dec81ab"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""d77e45b4-3885-48a7-ab5f-2656b2dd74cb"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""642e16ab-060f-46c1-a822-5a1ddc3b092b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""12e9aefb-e8b8-4a5c-b2da-9a71a4375fa4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""1aa24f3e-fbde-4da7-afa3-7fba88f35ddc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Flechas"",
                    ""id"": ""554f1ee2-cfc4-465d-ac04-459079f0da02"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""497f0a68-347a-4b91-806d-54997c179fdb"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9cde6d05-6faa-4a0c-88ea-c81db4510524"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WS"",
                    ""id"": ""5edb4e31-a064-4d0c-be06-5051bfee6e2f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2701a5a8-0507-4e2a-8aa5-1c9cbf3d2e1d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b6a46081-0843-41f3-b240-5cc606a68249"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d34ec1ed-3b9e-4396-b62a-38f6680fa943"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4c8f19d-16af-442c-8996-581f88562b05"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fa47f6e-5059-48b4-b267-f0e41e5d4c4c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42989074-8494-4d99-b36d-23f2ca80baa0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c42cc4ed-0e72-4201-b87d-0f787db298aa"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acelerar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""054b827b-3f92-4b2f-9a57-a8cc076eb890"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Desacelerar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Movimiento
        m_Movimiento = asset.FindActionMap("Movimiento", throwIfNotFound: true);
        m_Movimiento_Horizontal = m_Movimiento.FindAction("Horizontal", throwIfNotFound: true);
        m_Movimiento_Vertical = m_Movimiento.FindAction("Vertical", throwIfNotFound: true);
        m_Movimiento_move = m_Movimiento.FindAction("move", throwIfNotFound: true);
        m_Movimiento_Speed = m_Movimiento.FindAction("Speed", throwIfNotFound: true);
        m_Movimiento_Stop = m_Movimiento.FindAction("Stop", throwIfNotFound: true);
        m_Movimiento_Acelerar = m_Movimiento.FindAction("Acelerar", throwIfNotFound: true);
        m_Movimiento_Desacelerar = m_Movimiento.FindAction("Desacelerar", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Movimiento
    private readonly InputActionMap m_Movimiento;
    private IMovimientoActions m_MovimientoActionsCallbackInterface;
    private readonly InputAction m_Movimiento_Horizontal;
    private readonly InputAction m_Movimiento_Vertical;
    private readonly InputAction m_Movimiento_move;
    private readonly InputAction m_Movimiento_Speed;
    private readonly InputAction m_Movimiento_Stop;
    private readonly InputAction m_Movimiento_Acelerar;
    private readonly InputAction m_Movimiento_Desacelerar;
    public struct MovimientoActions
    {
        private @EntradaMovimiento m_Wrapper;
        public MovimientoActions(@EntradaMovimiento wrapper) { m_Wrapper = wrapper; }
        public InputAction @Horizontal => m_Wrapper.m_Movimiento_Horizontal;
        public InputAction @Vertical => m_Wrapper.m_Movimiento_Vertical;
        public InputAction @move => m_Wrapper.m_Movimiento_move;
        public InputAction @Speed => m_Wrapper.m_Movimiento_Speed;
        public InputAction @Stop => m_Wrapper.m_Movimiento_Stop;
        public InputAction @Acelerar => m_Wrapper.m_Movimiento_Acelerar;
        public InputAction @Desacelerar => m_Wrapper.m_Movimiento_Desacelerar;
        public InputActionMap Get() { return m_Wrapper.m_Movimiento; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovimientoActions set) { return set.Get(); }
        public void SetCallbacks(IMovimientoActions instance)
        {
            if (m_Wrapper.m_MovimientoActionsCallbackInterface != null)
            {
                @Horizontal.started -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnHorizontal;
                @Horizontal.performed -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnHorizontal;
                @Horizontal.canceled -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnHorizontal;
                @Vertical.started -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnVertical;
                @Vertical.performed -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnVertical;
                @Vertical.canceled -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnVertical;
                @move.started -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnMove;
                @move.performed -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnMove;
                @move.canceled -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnMove;
                @Speed.started -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnSpeed;
                @Speed.performed -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnSpeed;
                @Speed.canceled -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnSpeed;
                @Stop.started -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnStop;
                @Stop.performed -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnStop;
                @Stop.canceled -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnStop;
                @Acelerar.started -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnAcelerar;
                @Acelerar.performed -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnAcelerar;
                @Acelerar.canceled -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnAcelerar;
                @Desacelerar.started -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnDesacelerar;
                @Desacelerar.performed -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnDesacelerar;
                @Desacelerar.canceled -= m_Wrapper.m_MovimientoActionsCallbackInterface.OnDesacelerar;
            }
            m_Wrapper.m_MovimientoActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Horizontal.started += instance.OnHorizontal;
                @Horizontal.performed += instance.OnHorizontal;
                @Horizontal.canceled += instance.OnHorizontal;
                @Vertical.started += instance.OnVertical;
                @Vertical.performed += instance.OnVertical;
                @Vertical.canceled += instance.OnVertical;
                @move.started += instance.OnMove;
                @move.performed += instance.OnMove;
                @move.canceled += instance.OnMove;
                @Speed.started += instance.OnSpeed;
                @Speed.performed += instance.OnSpeed;
                @Speed.canceled += instance.OnSpeed;
                @Stop.started += instance.OnStop;
                @Stop.performed += instance.OnStop;
                @Stop.canceled += instance.OnStop;
                @Acelerar.started += instance.OnAcelerar;
                @Acelerar.performed += instance.OnAcelerar;
                @Acelerar.canceled += instance.OnAcelerar;
                @Desacelerar.started += instance.OnDesacelerar;
                @Desacelerar.performed += instance.OnDesacelerar;
                @Desacelerar.canceled += instance.OnDesacelerar;
            }
        }
    }
    public MovimientoActions @Movimiento => new MovimientoActions(this);
    public interface IMovimientoActions
    {
        void OnHorizontal(InputAction.CallbackContext context);
        void OnVertical(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnSpeed(InputAction.CallbackContext context);
        void OnStop(InputAction.CallbackContext context);
        void OnAcelerar(InputAction.CallbackContext context);
        void OnDesacelerar(InputAction.CallbackContext context);
    }
}
